spring:
  application:
    name: webstore
  jpa:
    hibernate.ddl-auto: create-drop
  datasource:
#    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
#    docker run --name mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=test -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -d -p 3306:3306 mysql/mysql-server:latest
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: user
    password: pass
    initialization-mode: always
