spring:
  application:
    name: webstore
  jpa.hibernate.ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: root
    password: root
    initialization-mode: always
